AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a PiHole EC2 Network Resources in AWS

Resources:
  PiHoleNetworkInterface0:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: 'PiHole EC2 Network Interface 0'
      GroupSet:
        - Fn::ImportValue: !Join [ '-', [ 'pihole-security-stack', Ref: AWS::Region, 'EC2-SecurityGroup-PiHoleEC2SecurityGroup-Id' ]]
        - Fn::ImportValue: !Join [ '-', [ 'edward-home-ec2-security-group-stack', Ref: AWS::Region, 'EdwardHome-EC2-SecurityGroup-Id' ]]
      Ipv6Addresses:
        - Ipv6Address:
            Fn::Sub:
              - '${NetworkPart}${HostPart}'
              - NetworkPart:
                  Fn::Select:
                    - '0'
                    - Fn::Split:
                        - '/64'
                        - Fn::ImportValue: !Join [ '-', [ 'vpc-stack', Ref: AWS::Region, 'PublicSubnet1', 'Ipv6CidrBlock' ]]
                HostPart: 10
      PrivateIpAddress:
        Fn::Sub:
          - '${NetworkPart}${HostPart}'
          - NetworkPart:
              Fn::Select:
                - '0'
                - Fn::Split:
                    - '0/24'
                    - Fn::ImportValue: !Join [ '-', [ 'vpc-stack', Ref: AWS::Region, 'PublicSubnet1', 'CidrBlock' ]]
            HostPart: 100
      SourceDestCheck: true
      SubnetId:
        Fn::ImportValue: !Join [ '-', [ 'vpc-stack', Ref: AWS::Region, 'PublicSubnet1', 'Id' ]]
      Tags:
        - Key: Name
          Value: !Join [ '-', [ Ref: AWS::StackName, Ref: AWS::Region, 'PiHole', 'NetworkInterfaces' ]]

  # EC2 EIP Association
  PiHoleEC2EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId:
        Fn::ImportValue: !Join [ '-', [ 'ec2-eip-stack', Ref: AWS::Region, 'EIP1', 'AllocationId' ]]
      NetworkInterfaceId: !GetAtt PiHoleNetworkInterface0.Id

Outputs:
  PiHoleNetworkInterface0Ref:
    Value: !Ref PiHoleNetworkInterface0
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-NetworkInterface-PiHoleNetworkInterface0-Ref'
  PiHoleNetworkInterface0Id:
    Value: !GetAtt PiHoleNetworkInterface0.Id
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-NetworkInterface-PiHoleNetworkInterface0-Id'
  PiHoleNetworkInterface0PrimaryPrivateIpAddress:
    Value: !GetAtt PiHoleNetworkInterface0.PrimaryPrivateIpAddress
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-NetworkInterface-PiHoleNetworkInterface0-PrimaryPrivateIpAddress'
  PiHoleEC2EIPAssociationRef:
    Value: !Ref PiHoleEC2EIPAssociation
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-EIPAssociation-PiHoleEC2EIPAssociation-Ref'
  PiHoleEC2EIPAssociationId:
    Value: !GetAtt PiHoleEC2EIPAssociation.Id
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-EIPAssociation-PiHoleEC2EIPAssociation-Id'