AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a PiHole EC2 DNS Resources in AWS

Parameters:
  EC2InstanceId:
    Description: The Id of the EC2 Instance
    Type: String

Resources:
  # EC2 EIP Association
  PiHoleEC2EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId:
        Fn::ImportValue: !Join [ '-', [ 'ec2-eip-stack', Ref: AWS::Region, 'EC2-EIP-ElasticIP1-AllocationId' ]]
      InstanceId: !Sub ${EC2InstanceId}

Outputs:
  PiHoleEC2EIPAssociationRef:
    Value: !Ref PiHoleEC2EIPAssociation
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-EIPAssociation-PiHoleEC2EIPAssociation-Ref'
  PiHoleEC2EIPAssociationId:
    Value: !GetAtt PiHoleEC2EIPAssociation.Id
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-EIPAssociation-PiHoleEC2EIPAssociation-Id'
  PiHoleEC2InstancePublicDnsName:
    Value: !GetAtt PiHoleEC2Instance.PublicDnsName
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-Instance-PiHoleEC2Instance-PublicDnsName'
  PiHoleEC2InstancePublicIp:
    Value: !GetAtt PiHoleEC2Instance.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-Instance-PiHoleEC2Instance-PublicIp'
