AWSTemplateFormatVersion: '2010-09-09'
Description: Create LogGroups

Resources:
  ChengSydneyHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: String
      HostedZoneTags:
        - Key: String
          Value: String
      Name: String
      QueryLoggingConfig:
        QueryLoggingConfig
      VPCs:
        - VPC

Outputs:
  CloudFormationLogGroupRef:
    Value: !Ref CloudFormationLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-Logs-LogGroup-CloudFormationLogGroup-Ref'
  CloudFormationLogGroupArn:
    Value: !GetAtt CloudFormationLogGroup.Arn
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-Logs-LogGroup-CloudFormationLogGroup-Arn'
  EC2LogGroupRef:
    Value: !Ref EC2LogGroup
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-Logs-LogGroup-EC2LogGroup-Ref'
  EC2LogGroupArn:
    Value: !GetAtt EC2LogGroup.Arn
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-Logs-LogGroup-EC2LogGroup-Arn'