AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the EC2 Elastic IP Addresses

Resources:
  ElasticIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: standard
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-${AWS::Region}-EC2-EIP-ElasticIP1'

  NatInstanceElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: standard
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-${AWS::Region}-EC2-EIP-NatInstanceElasticIP'

Outputs:
  ElasticIP1Ref:
    Value: !Ref ElasticIP1
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-EIP-ElasticIP1-Ref'
  ElasticIP1AllocationId:
    Value: !GetAtt ElasticIP1.AllocationId
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-EIP-ElasticIP1-AllocationId'
  ElasticIP1PublicIp:
    Value: !GetAtt ElasticIP1.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-EIP-ElasticIP1-PublicIp'
  NatInstanceElasticIPRef:
    Value: !Ref NatInstanceElasticIP
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-EIP-NatInstanceElasticIP-Ref'
  NatInstanceElasticIPAllocationId:
    Value: !GetAtt NatInstanceElasticIP.AllocationId
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-EIP-NatInstanceElasticIP-AllocationId'
  NatInstanceElasticIPPublicIp:
    Value: !GetAtt NatInstanceElasticIP.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-EIP-NatInstanceElasticIP-PublicIp'