AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the EC2 Elastic IP Addresses

Resources:
  ElasticIP1:
    Type: AWS::EC2::EIP
    Domain: standard
    Tags:
      - Key: Name
        Value: !Sub '${AWS::StackName}-ElasticIP1'

Outputs:
  EIPAllocationId1:
    Value: !GetAtt ElasticIP1.AllocationId
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EIP1-AllocationId'
  EIPPublicIp1:
    Value: !GetAtt ElasticIP1.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EIP1-PublicIp'