AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a EC2 Key Pair and saved it to AWS Systems Manager Parameter Store with format /ec2/keypair/key_pair_id

Parameters:
  KeyFormat:
    Description: The format of the key pair.
    Type: String
    Default: pem
  KeyName:
    Description: Name of the EC2 Key Pair
    Type: String
    Default: ec2-key-pair
  KeyType:
    Description: The type of key pair to create.
    Type: String
    Default: rsa

Resources:
  EC2KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyFormat: !Ref KeyFormat
      KeyName: !Ref KeyName
      KeyType: !Ref KeyType
      Tags:
        - Key: KeyPair
          Value: !Join [ '-', [ 'EC2KeyPair', Ref: AWS::Region, Ref: KeyFormat, Ref: KeyName, Ref: KeyType ]]

Outputs:
  EC2KeyPairRef:
    Value: !Ref NewKeyPair
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-KeyPair-EC2KeyPair-Ref'
  EC2KeyPairKeyFingerprint:
    Value: !GetAtt NewKeyPair.KeyFingerprint
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-KeyPair-EC2KeyPair-KeyFingerprint'
  EC2KeyPairKeyPairId:
    Value: !GetAtt EC2KeyPair.KeyPairId
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-KeyPair-EC2KeyPair-KeyPairId'

# Notes:
# 1. Following CLI command can be used to get the ID of the key pair after it is created:
# aws ec2 describe-key-pairs --filters Name=key-name,Values=YOUR_KEY_NAME --query KeyPairs[*].KeyPairId --output text
# 2. Following CLI command can be used to et the parameter for your key and save the key material in a .pem file:
# aws ssm get-parameter --name /ec2/keypair/YOUR_KEY_PAIR_ID --with-decryption --query Parameter.Value --output text > new-key-pair.pem