AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 Security Group with ingress and egress rules from Edward's Home

Parameters:
  EdwardHomeSGIngressCidrIp:
    Description: The CidrIp for the SG EdwardHomeSecurityGroup Ingress
    Type: String
  EdwardHomeSGIngressCidrIpv6:
    Description: The CidrIpv6 for the SG EdwardHomeSecurityGroup Ingress
    Type: String

Resources:
  EdwardHomeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Edward Home Security Group
      SecurityGroupIngress:
        - CidrIp: !Ref EdwardHomeSGIngressCidrIp
          Description: Allow inbound SSH connection from Edward Home
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        - CidrIpv6: !Ref EdwardHomeSGIngressCidrIpv6
          Description: Allow inbound SSH connection from Edward Home
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
      Tags:
        - Key: EdwardHomeSecurityGroup
          Value: !Join [ '-', [ Ref: AWS::StackName, 'SecurityGroup', 'EdwardHome' ]]
      VpcId:
        Fn::ImportValue: !Sub 'general-vpc-stack-${AWS::Region}-EC2-VPC-GeneralVpc-VpcId'

Outputs:
  EdwardHomeSecurityGroupRef:
    Value: !Ref EdwardHomeSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-SecurityGroup-EdwardHomeSecurityGroup-Ref'
  EdwardHomeSecurityGroupGroupId:
    Value: !GetAtt EdwardHomeSecurityGroup.GroupId
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-SecurityGroup-EdwardHomeSecurityGroup-GroupId'
  EdwardHomeSecurityGroupVpcId:
    Value: !GetAtt EdwardHomeSecurityGroup.VpcId
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-EC2-SecurityGroup-EdwardHomeSecurityGroup-VpcId'