---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 Bucket

Resources:
  DeleteFromS3ActionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: test-delete-from-s3-action
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  DeleteFromS3ActionBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DeleteFromS3ActionBucket
      PolicyDocument:
        Id: DeleteFromS3ActionBucketPolicyDocument
        Version: '2012-10-17'
        Statement:
          - Sid: DeleteFromS3ActionBucketPolicyDocumentStatement
            Effect: Allow
            AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:*'
            Action:
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:DeleteObject'
            Resource:
              - Fn::Join: [ '', [ 'arn:aws:s3:::', !Ref DeleteFromS3ActionBucket ] ]
              - Fn::Join: [ '', [ 'arn:aws:s3:::', !Ref DeleteFromS3ActionBucket, '/*' ] ]
          - Sid: DeleteFromS3ActionBucketPolicyDocumentStatement2
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:*'
            Action:
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:DeleteObject'
            Resource:
              - Fn::Join: [ '', [ 'arn:aws:s3:::', !Ref DeleteFromS3ActionBucket ] ]
              - Fn::Join: [ '', [ 'arn:aws:s3:::', !Ref DeleteFromS3ActionBucket, '/*' ] ]

  CloudFormationTemplatesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cloudformation-templates-shared-files
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudFormationTemplatesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudFormationTemplatesBucket
      PolicyDocument:
        Id: CloudFormationTemplatesBucketPolicyDocument
        Version: '2012-10-17'
        Statement:
          - Sid: CloudFormationTemplatesBucketPolicyDocumentStatement
            Effect: Allow
            AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:*'
            Action:
              - 's3:GetObject'
              - 's3:ListBucket'
            Resource:
              - Fn::Join: [ '', [ 'arn:aws:s3:::', !Ref CloudFormationTemplatesBucket ] ]
              - Fn::Join: [ '', [ 'arn:aws:s3:::', !Ref CloudFormationTemplatesBucket, '/*' ] ]
          - Sid: CloudFormationTemplatesBucketPutBucketPolicyDocumentStatement
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:*'
            Action:
              - 's3:PutBucketPolicy'
            Resource:
              - Fn::Join: [ '', [ 'arn:aws:s3:::', !Ref CloudFormationTemplatesBucket ] ]
              - Fn::Join: [ '', [ 'arn:aws:s3:::', !Ref CloudFormationTemplatesBucket, '/*' ] ]

Outputs:
  DeleteFromS3ActionBucketArn:
    Value: !GetAtt DeleteFromS3ActionBucket.Arn
    Export:
      Name: DeleteFromS3ActionBucketArn
  CloudFormationTemplatesBucketArn:
    Value: !GetAtt CloudFormationTemplatesBucket.Arn
    Export:
      Name: CloudFormationTemplatesBucketArn