---
AWSTemplateFormatVersion: "2010-09-09"
Description: Create IAM Super Admin Users

Resources:
  ECSuperUser:
    Type: AWS::IAM::User
    Properties:
        Groups:
          - !Ref SuperAdminGroup

  SuperAdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName:
        Fn::Join:
          - "-"
          - - "super-admin-group"
            - !Ref "AWS::Region"
      Policies:
        - PolicyName:
            Fn::Join:
              - "-"
              - - "super-admin-policy"
                - !Ref "AWS::Region"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
      Path: "/"

  PutBucketPolicyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Join:
          - "-"
          - - "PutBucketPolicyRole"
            - !Ref "AWS::Region"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:aws:iam::"
                    - !Ref "AWS::AccountId"
                    - ":root"
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName:
            Fn::Join:
              - "-"
              - - "PutBucketPolicyPolicy"
                - !Ref "AWS::Region"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:*"
                  - "s3:PutBucketPolicy"
                  - "cloudformation:*"
                Resource: "*"

  ECSuperUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: 1
      Status: Active
      UserName: !Ref ECSuperUser

  ECSuperUserAccessKeySecretsManagerStored:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ec-super-user-access-key
      SecretString: !Sub '{"ACCESS_KEY":"${ECSuperUserAccessKey}","SECRET_KEY":"${ECSuperUserAccessKey.SecretAccessKey}"}'