AWSTemplateFormatVersion: '2010-09-09'
Description: Create Instance Profiles

Resources:
  LogRoleInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: !Ref LogRole
  
    LogRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal:
                Service: 'ec2.amazonaws.com'
          Action:
            - 'sts:AssumeRole'
        Path: /
        Policies:
          - PolicyName: 'LogRolePolicy'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: 'Allow'
                  Action:
                    - 'logs:CreateLogGroup'
                    - 'logs:CreateLogStream'
                    - 'logs:PutLogEvents'
                    - 'logs:DescribeLogStreams'
                  Resource:
                    - Fn::Join:
                        - ''
                        - - 'arn:aws:'
                          - ':logs:*:*:*'