---
AWSTemplateFormatVersion: "2010-09-09"
Description: Create IAM Super Admin Users

Resources:
  ECSuperUser:
    Type: AWS::IAM::User
    Properties:
        Groups:
          - !Ref SuperAdminGroup

  SuperAdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName:
        Fn::Join:
          - "-"
          - - "super-admin-group"
            - !Ref "AWS::Region"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Path: "/"
      Policies:
        - PolicyDocument: {
            "Version" : "2012-10-17",
            "Id": "SuperAdminPutBucketPolicyDocument",
            "Statement" : [
              {
                "Sid" : "SuperAdminPutBucketPolicy",
                "Effect" : "Allow",
                "Action" : [
                  "s3:PutBucketPolicy"
                ],
                "Resource": "arn:aws:s3:::*"
              }
            ]
          }
          PolicyName: SuperAdminPutBucketPolicy

  ECSuperUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: 1
      Status: Active
      UserName: !Ref ECSuperUser
