AWSTemplateFormatVersion: '2010-09-09'
Description: >
  VPC infrastructure stack. A Vpc with 2 public and 2 private subnet will be created, in which the subnet 1 will be the 
  IPv4 and IPv6 dual stack subnet, the subnet 2 will be the IPv4 only subnet (The IPv6 only subnet creation is not 
  supported by CloudFormation yet, only via console or CLI).
Parameters:
  Category:
    Description: The category of VPC
    Type: String
    Default: GENERAL
    AllowedValues:
      - GENERAL
Mappings:
  VpcCidrBlock:
    GENERAL:
      CidrBlock: 10.1.0.0/16
  SubnetCidrBlock:
    GENERAL:
      Public1: 10.1.1.0/24
      Public2: 10.1.2.0/24
      Private1: 10.1.10.0/24
      Private2: 10.1.20.0/24
      Ipv6SubnetPublic1: 01::/64
      Ipv6SubnetPrivate1: 10::/64

Resources:
  # VPC
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !FindInMap [ VpcCidrBlock, Ref: Category, CidrBlock ]
      Tags:
        - Key: Category
          Value: !Ref Category
        - Key: Name
          Value: !Join [ '-', [ Ref: AWS::StackName, Ref: Category, 'Vpc' ]]
  IPv6CidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      AmazonProvidedIpv6CidrBlock: true
      VpcId: !Ref Vpc
  EgressOnlyInternetGateway:
    Type: AWS::EC2::EgressOnlyInternetGateway
    Properties:
      VpcId: !Ref Vpc

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Category
          Value: !Ref Category
        - Key: Name
          Value: !Join [ '-', [ Ref: AWS::StackName, Ref: Category, 'InternetGateway' ]]
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

  # Routing - public subnet 1 and 2
  PublicSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Category
          Value: !Ref Category
        - Key: Name
          Value: !Join [ '-', [ Ref: AWS::StackName, Ref: Category, 'RouteTable', 'PublicSubnet1' ]]
  PublicSubnet1Route:
    DependsOn: InternetGatewayAttachment
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicSubnet1RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PublicSubnet1Ipv6Route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicSubnet1RouteTable
      DestinationIpv6CidrBlock: ::/0
      GatewayId: !Ref InternetGateway
  PublicSubnet2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Category
          Value: !Ref Category
        - Key: Name
          Value: !Join [ '-', [ Ref: AWS::StackName, Ref: Category, 'RouteTable', 'PublicSubnet2' ]]
  PublicSubnet2Route:
    DependsOn: InternetGatewayAttachment
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicSubnet2RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway


  # Routing - private subnet 1 and 2
  PrivateSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Category
          Value: !Ref Category
        - Key: Name
          Value: !Join [ '-', [ Ref: AWS::StackName, Ref: Category, 'RouteTable', 'PrivateSubnet1' ] ]
  PrivateSubnet1Ipv6Route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateSubnet1RouteTable
      DestinationIpv6CidrBlock: ::/0
      EgressOnlyInternetGatewayId: !Ref EgressOnlyInternetGateway
  PrivateSubnet2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Category
          Value: !Ref Category
        - Key: Name
          Value: !Join [ '-', [ Ref: AWS::StackName, Ref: Category, 'RouteTable', 'PrivateSubnet2' ] ]

  # Access control
  PrivateSubnetsNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Category
          Value: !Ref Category
        - Key: Name
          Value: !Join [ '-', [ Ref: AWS::StackName, Ref: Category, 'NetworkAcl' ]]
  PrivateSubnetsNetworkAclInboundEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateSubnetsNetworkAcl
      RuleNumber: 1
      PortRange:
        From: 22 # SSH
        To: 22
      Protocol: 6 # TCP
      RuleAction: allow
      Egress: false
      CidrBlock: !FindInMap [ VpcCidrBlock, Ref: Category, CidrBlock ]
  PrivateSubnetsNetworkAclOutboundEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateSubnetsNetworkAcl
      RuleNumber: 2
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0
  PrivateSubnetsNetworkAclIpv6OutboundEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateSubnetsNetworkAcl
      RuleNumber: 3
      Protocol: -1
      RuleAction: allow
      Egress: true
      Ipv6CidrBlock: ::/0

  # Public subnet 1 and 2
  PublicSubnet1:
    DependsOn: IPv6CidrBlock
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !FindInMap [ SubnetCidrBlock, Ref: Category, Public1 ]
      Ipv6CidrBlock:
        Fn::Sub:
          - '${VpcPart}${SubnetPart}'
          - VpcPart: !Select [ '0', !Split [ '00::/56', !Select [ '0', !GetAtt Vpc.Ipv6CidrBlocks ]]]
            SubnetPart: !FindInMap [ SubnetCidrBlock, Ref: Category, Ipv6SubnetPublic1 ]
      AssignIpv6AddressOnCreation: true
      AvailabilityZone: !Sub '${AWS::Region}a'
      Tags:
        - Key: Category
          Value: !Ref Category
        - Key: Name
          Value: !Join [ '-', [ Ref: AWS::StackName, Ref: Category, 'Subnet', 'Public1' ]]
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicSubnet1RouteTable
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !FindInMap [ SubnetCidrBlock, Ref: Category, Public2 ]
      AvailabilityZone: !Sub '${AWS::Region}b'
      Tags:
        - Key: Category
          Value: !Ref Category
        - Key: Name
          Value: !Join [ '-', [ Ref: AWS::StackName, Ref: Category, 'Subnet', 'Public2' ]]
  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicSubnet2RouteTable

  # Private subnet 1 and 2
  PrivateSubnet1:
    DependsOn: IPv6CidrBlock
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !FindInMap [ SubnetCidrBlock, Ref: Category, Private1 ]
      Ipv6CidrBlock:
        Fn::Sub:
          - '${VpcPart}${SubnetPart}'
          - VpcPart: !Select [ '0', !Split [ '00::/56', !Select [ '0', !GetAtt Vpc.Ipv6CidrBlocks ] ] ]
            SubnetPart: !FindInMap [ SubnetCidrBlock, Ref: Category, Ipv6SubnetPrivate1 ]
      AssignIpv6AddressOnCreation: true
      AvailabilityZone: !Sub '${AWS::Region}a'
      Tags:
        - Key: Category
          Value: !Ref Category
        - Key: Name
          Value: !Join [ '-', [ Ref: AWS::StackName, Ref: Category, 'Subnet', 'Private1' ]]
  PrivateSubnet1AclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref PrivateSubnetsNetworkAcl
      SubnetId: !Ref PrivateSubnet1
  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateSubnet1RouteTable
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !FindInMap [ SubnetCidrBlock, Ref: Category, Private2 ]
      AvailabilityZone: !Sub '${AWS::Region}b'
      Tags:
        - Key: Category
          Value: !Ref Category
        - Key: Name
          Value: !Join [ '-', [ Ref: AWS::StackName, Ref: Category, 'Subnet', 'Private2' ]]
  PrivateSubnet2AclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref PrivateSubnetsNetworkAcl
      SubnetId: !Ref PrivateSubnet2
  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateSubnet2RouteTable

Outputs:
  VpcId:
    Value: !Ref Vpc
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-VpcId'
  VpcCidrBlock:
    Value: !GetAtt Vpc.CidrBlock
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-VpcCidrBlock'
  VpcIpv6CidrBlock:
    Value: !Select [ '0', !GetAtt Vpc.Ipv6CidrBlocks ]
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-VpcIpv6CidrBlock'
  PublicSubnet1Id:
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-PublicSubnet1Id'
  PublicSubnet1AvailabilityZone:
    Value: !GetAtt PublicSubnet1.AvailabilityZone
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-PublicSubnet1AvailabilityZone'
  PublicSubnet1Ipv6CidrBlock:
    Value: !Select [ '0', !GetAtt PublicSubnet1.Ipv6CidrBlocks ]
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-PublicSubnet1Ipv6CidrBlock'
  PublicSubnet2Id:
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-PublicSubnet2Id'
  PublicSubnet2AvailabilityZone:
    Value: !GetAtt PublicSubnet2.AvailabilityZone
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-PublicSubnet2AvailabilityZone'
  PrivateSubnet1Id:
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-PrivateSubnet1Id'
  PrivateSubnet1AvailabilityZone:
    Value: !GetAtt PrivateSubnet1.AvailabilityZone
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-PrivateSubnet1AvailabilityZone'
  PrivateSubnet2Id:
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-PrivateSubnet2Id'
  PrivateSubnet2AvailabilityZone:
    Value: GetAtt PrivateSubnet2.AvailabilityZone
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-PrivateSubnet2AvailabilityZone'
  Category:
    Description: Category name of stack
    Value: !Ref Category
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-Category'
  PublicSubnet1RouteTableId:
    Value: !Ref PublicSubnet1RouteTable
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-PublicSubnet1RouteTableId'
  PublicSubnet2RouteTableId:
    Value: !Ref PublicSubnet2RouteTable
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-PublicSubnet2RouteTableId'
  PrivateSubnet1RouteTableId:
    Value: !Ref PrivateSubnet1RouteTable
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-PrivateSubnet1RouteTableId'
  PrivateSubnet2RouteTableId:
    Value: !Ref PrivateSubnet2RouteTable
    Export:
      Name: !Sub '${AWS::StackName}-${AWS::Region}-PrivateSubnet2RouteTableId'
