name: IAM Super User Stack

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        type: choice
        default: 'ap-southeast-2'
        options:
          - 'us-east-1'
          - 'us-east-2'
          - 'us-west-1'
          - 'us-west-2'
          - 'ap-south-1'
          - 'ap-northeast-1'
          - 'ap-northeast-2'
          - 'ap-northeast-3'
          - 'ap-southeast-1'
          - 'ap-southeast-2'
          - 'ca-central-1'
          - 'eu-central-1'
          - 'eu-west-1'
          - 'eu-west-2'
          - 'eu-west-3'
          - 'eu-north-1'

permissions:
  id-token: write
  contents: write

jobs:
  create-s3:
    name: Create / Update S3 Resources
    runs-on: ubuntu-latest
    environment: AWS
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region}}
      - name: Deploy IAM stack with CloudFormation
        id: iam-user-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: iam-super-user-stack
          template: iam/iam-super-user-template.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM