name: Sync shared static files to S3

on:
  workflow_dispatch:

jobs:
  upload:
    name: Sync shared static files to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync shared static files to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --exclude 'README.md'
        env:
          AWS_S3_BUCKET: 'cloudformation-templates-shared-files'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'
          SOURCE_DIR: 's3-static-files'